import Head from 'next/head'
import Content from '../components/Content'
import Header from '../components/Header'

export default function Home() {
  return (
    <div className={`
    flex flex-col items-center h-full p-3
    bg-red-400`}>
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/icone.svg" />
      </Head>
      <Header 
      title='Pokédex'
      subtitle='Pesquisa avançada de Pokémons'
      />
      <Content/>
    </div>
  )
}
