import Head from 'next/head'
import Content from '../components/Content'
import Header from '../components/Header'
import { useScrollData } from '../hook/useScrollData'

export default function Home() {

  const { refTop } = useScrollData()

  return (
    <div className={`
    flex flex-col items-center min-h-screen max-h-full p-3
    bg-gradient-to-b from-red-400 to-red-500`} id='inicio' ref={refTop}>
      <Head>
        <title>Pokédex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/images/icone.svg" />
      </Head>
      <Header 
      title='Pokédex'
      subtitle='Pesquisa avançada de Pokémons'
      />
      <Content/>
    </div>
  )
}
