import Head from "next/head";
import { useScrollData } from "../hook/useScrollData";
import Content from "./Content";
import Header from "./Header";

interface LayoutProps {
    children: any
}

export default function Layout(props: LayoutProps) {

    const { refTop } = useScrollData()

    return (
        <div className={`
    flex flex-col items-center min-h-screen max-h-full p-3
    bg-gradient-to-b from-red-400 to-red-500
    `}
      id='inicio' ref={refTop}>
            <Head>
                <title>Pokédex</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/images/icone.svg" />
            </Head>
            <Header
                title='Pokédex'
                subtitle='Pesquisa Avançada de Pokémons'
            />
            <Content>
                {props.children}
            </Content>
        </div>
    )
}